### ISSUE TITLE
wine: failed to open "./Cred.exe": c0000135

### ISSUE THREAD

**Issue by SSUPII** [Algebro7/PTCGLTokenExtractor#1]
[wine-7.0] Creds.exe is crashing with c0000135 with no further information while trying to write.
Wineprefix has this winetricks done: `dxvk vcrun2019 corefonts`

**Comment by Algebro7** [comment]
Thanks, are you able to post the output from the command line?

**Comment by SSUPII** [comment]
```
sergio@debian:~/Desktop$ WINEPREFIX=/home/sergio/Games/PokemonTCGLive wine ./Cred.exe write TOKEN-HERE
wine: failed to open "./Cred.exe": c0000135
sergio@debian:~/Desktop$
```

That is it

**Comment by SSUPII** [comment]
Nevermind, I was trying ot run a non-existing `Cred.exe` instead of `Creds.exe`
